name: Build and Test
on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  create-env:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
        
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        
      - name: create environment with conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: cryptkeeper
          environment-file: environment.yml
      
      - name: check solution
        run: |
          conda env export
      - name: install ostir
        run: |
          pip install ./
      
      - name: test ostir
        run: |
          which ostir
          python -m unittest
